### ISSUE TITLE
Error: Cannot find module 'lodash/lang/isFunction'

### ISSUE THREAD

**Issue by wxg4net** [Gargron/xmpp-web#2]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'start' ]
2 info using npm@2.14.3
3 info using node@v0.10.36
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart xmpp-web@1.0.0
6 info start xmpp-web@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info xmpp-web@1.0.0 Failed to exec start script
9 verbose stack Error: xmpp-web@1.0.0 start: `webpack-dev-server --config webpack-dev-server.config.js --progress --inline --colors`
9 verbose stack Exit status 8
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at EventEmitter.emit (events.js:98:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:766:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
10 verbose pkgid xmpp-web@1.0.0
11 verbose cwd /home/web/site/im.perhome.cn
12 error Linux 2.6.32-042stab094.7
13 error argv "node" "/usr/bin/npm" "start"
14 error node v0.10.36
15 error npm  v2.14.3
16 error code ELIFECYCLE
17 error xmpp-web@1.0.0 start: `webpack-dev-server --config webpack-dev-server.config.js --progress --inline --colors`
17 error Exit status 8
18 error Failed at the xmpp-web@1.0.0 start script 'webpack-dev-server --config webpack-dev-server.config.js --progress --inline --colors'.
18 error This is most likely a problem with the xmpp-web package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server --config webpack-dev-server.config.js --progress --inline --colors
18 error You can get their info via:
18 error     npm owner ls xmpp-web
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by wxg4net** [comment]
ENV: Centos 6.5

**Comment by wxg4net** [comment]
npm WARN package.json xmpp-web@1.0.0 No repository field.

**Comment by Gargron** [comment]
Have you `git clone`d this repository and then run `npm install` first? Just making sure because this isn't supposed to be a package you can just `npm install xmpp-web` or something.

**Comment by wxg4net** [comment]
thx
